version: 1
backend:
  phases:
    build:
      commands:
        - echo "No backend build steps required for a Spring Boot application"
  artifacts:
    baseDirectory: target
    files:
      - '**/*'
  cache:
    paths:
      - ~/.m2/repository/**/*
      
deploy:
  artifacts:
    baseDirectory: target
    files:
      - '**/*'
  backend:
    phases:
      build:
        commands:
          - echo "No backend build steps required for a Spring Boot application"
    artifacts:
      baseDirectory: target
      files:
        - '**
