name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Amplify
      run: amplify publish
      env:
        AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
        # AMPLIFY_API_ID: ${{ secrets.AMPLIFY_API_ID }}
        # AMPLIFY_BRANCH: ${{ secrets.AMPLIFY_BRANCH }}
        # AMPLIFY_TOKEN: ${{ secrets.AMPLIFY_TOKEN }}
