version: 1
frontend:
  phases:
    # Specifies the build configuration for the frontend
    build:
      commands:
        - npm install
        - npm run build
  artifacts:
    # Defines the build output directory and files to be uploaded
    baseDirectory: build
    files:
      - '**/*'
  cache:
    # Configures caching behavior to speed up build time
    paths:
      - node_modules/**/*
