version: 1
frontend:
  phases:
    build:
      commands:
        - echo "No frontend build steps required for a Spring Boot application"
  artifacts:
    baseDirectory: target
    files:
      - '**/*'
  cache:
    paths:
      - ~/.m2/repository/**/*
      
deploy:
  artifacts:
    # Specifies the build output directory and files to be uploaded
    baseDirectory: target
    files:
      - '**/*'
  backend:
    phases:
      # Specifies the build configuration for the backend
      build:
        commands:
          - echo "No backend build steps required for a Spring Boot application"
    artifacts:
      # Defines the build output directory and files to be uploaded
      baseDirectory: target
      files:
        - '**/*'
  cache:
    # Configures caching behavior to speed up build time
    paths:
      - ~/.m2/repository/**/*
