name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure AWS credentials
        run: amplify configure

      - name: Deploy to Amplify
        run: amplify publish
